name: najm
description: "نجم - مرشدك الذكي لتحقيق الأحلام والأهداف وبناء العادات"
publish_to: "none"
version: 4.1.0+5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^22.2.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
