import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'v4_app.dart';

class NajmV5App extends StatelessWidget {
  const NajmV5App({super.key});
  @override Widget build(BuildContext context)=>MaterialApp(
    debugShowCheckedModeBanner:false,title:'نجم',theme:ThemeData(brightness:Brightness.dark,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:gold,brightness:Brightness.dark),useMaterial3:true),home:const V5Gate());
}

class V5Gate extends StatefulWidget { const V5Gate({super.key}); @override State<V5Gate> createState()=>_V5GateState(); }
class _V5GateState extends State<V5Gate>{ StreamSubscription<AuthState>? sub; @override void initState(){super.initState();sub=Supabase.instance.client.auth.onAuthStateChange.listen((_){if(mounted)setState((){});});} @override void dispose(){sub?.cancel();super.dispose();} @override Widget build(BuildContext c)=>Supabase.instance.client.auth.currentSession==null?const AuthPage():const V5Shell(); }

class V5Shell extends StatefulWidget { const V5Shell({super.key}); @override State<V5Shell> createState()=>_V5ShellState(); }
class _V5ShellState extends State<V5Shell>{
  final sb=Supabase.instance.client; NajmStateData data=NajmStateData(); bool loading=true,saving=false; int tab=0,focusToday=0,xp=0; List<String> top=[]; List<Map<String,String>> chat=[]; Timer? timer;
  @override void initState(){super.initState();load();} @override void dispose(){timer?.cancel();super.dispose();}
  Future<void> load() async { final u=sb.auth.currentUser!; try{final r=await sb.from('app_state').select('data').eq('user_id',u.id).maybeSingle(); if(r!=null&&r['data'] is Map){final m=Map<String,dynamic>.from(r['data']);data=NajmStateData.fromJson(m);final v=Map<String,dynamic>.from((m['v5'] as Map?)??{});focusToday=(v['focusToday'] as num?)?.toInt()??0;xp=(v['xp'] as num?)?.toInt()??0;top=List<String>.from(v['top']??[]);chat=((v['chat'] as List?)??[]).map((e)=>Map<String,String>.from(e)).toList();} else {data.displayName='${u.userMetadata?['display_name']??u.email?.split('@').first??'صديقي'}';}}catch(_){final p=await SharedPreferences.getInstance();final raw=p.getString('najm_v5_${u.id}');if(raw!=null){final m=Map<String,dynamic>.from(jsonDecode(raw));data=NajmStateData.fromJson(m);}} rebuild(); if(mounted)setState(()=>loading=false); }
  Map<String,dynamic> full(){final m=data.toJson();m['v5']={'focusToday':focusToday,'xp':xp,'top':top,'chat':chat};return m;}
  Future<void> save() async {final u=sb.auth.currentUser;if(u==null)return;if(mounted)setState(()=>saving=true);final m=full();final p=await SharedPreferences.getInstance();await p.setString('najm_v5_${u.id}',jsonEncode(m));try{await sb.from('app_state').upsert({'user_id':u.id,'data':m,'updated_at':DateTime.now().toUtc().toIso8601String()});}catch(_){}if(mounted)setState(()=>saving=false);}
  void changed([int add=1]){xp+=add;setState((){});timer?.cancel();timer=Timer(const Duration(milliseconds:400),save);}
  void rebuild(){top.removeWhere((id)=>!data.tasks.any((t)=>t.id==id&&!t.done));final xs=[...data.tasks.where((t)=>!t.done)]..sort((a,b)=>b.priority.compareTo(a.priority));for(final t in xs){if(top.length>=3)break;if(!top.contains(t.id))top.add(t.id);}}
  TaskItem? get next {rebuild();for(final id in top){for(final t in data.tasks){if(t.id==id&&!t.done)return t;}}return null;}
  int get score{var s=0;if(data.tasks.isNotEmpty)s+=(data.tasks.where((t)=>t.done).length/data.tasks.length*50).round();if(data.habits.isNotEmpty)s+=(data.habits.where((h)=>h.checkedDay==dayKey()).length/data.habits.length*25).round();if(data.dreams.isNotEmpty)s+=(data.dreams.where((d)=>d.readToday).length/data.dreams.length*10).round();s+=focusToday>=25?15:(focusToday/25*15).round();return s.clamp(0,100);} 
  Widget box(Widget child)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:panel,borderRadius:BorderRadius.circular(22),border:Border.all(color:border)),child:child);
  Widget title(String t,String s)=>Padding(padding:const EdgeInsets.only(bottom:10,top:4),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Text(s,style:const TextStyle(color:Colors.white54))]));
  Widget page(List<Widget> c)=>ListView(padding:const EdgeInsets.fromLTRB(16,8,16,110),children:c);
  @override Widget build(BuildContext c){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator(color:gold)));final pages=[home(),goals(),vision(),habits(),coach()];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(backgroundColor:bg,title:Row(children:[const Text('نجم',style:TextStyle(color:gold2,fontWeight:FontWeight.w900,fontSize:25)),if(saving)...[const SizedBox(width:10),const SizedBox(width:13,height:13,child:CircularProgressIndicator(strokeWidth:2,color:gold))]]),actions:[IconButton(onPressed:()=>sb.auth.signOut(),icon:const Icon(Icons.logout))]),body:SafeArea(top:false,child:IndexedStack(index:tab,children:pages)),floatingActionButton:tab==0?FloatingActionButton.extended(backgroundColor:gold,foregroundColor:Colors.black,onPressed:addTask,icon:const Icon(Icons.add),label:const Text('مهمة')):null,bottomNavigationBar:SafeArea(top:false,child:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),backgroundColor:panel,indicatorColor:const Color(0x33E8B84E),destinations:const [NavigationDestination(icon:Icon(Icons.bolt_outlined),selectedIcon:Icon(Icons.bolt,color:gold),label:'الآن'),NavigationDestination(icon:Icon(Icons.flag_outlined),selectedIcon:Icon(Icons.flag,color:gold),label:'أهدافي'),NavigationDestination(icon:Icon(Icons.auto_awesome_outlined),selectedIcon:Icon(Icons.auto_awesome,color:gold),label:'رؤيتي'),NavigationDestination(icon:Icon(Icons.loop_outlined),selectedIcon:Icon(Icons.loop,color:gold),label:'عاداتي'),NavigationDestination(icon:Icon(Icons.psychology_outlined),selectedIcon:Icon(Icons.psychology,color:gold),label:'مرشدي')]))));}
  Widget home(){final n=next;final ts=top.map((id)=>data.tasks.where((t)=>t.id==id).toList()).where((x)=>x.isNotEmpty).map((x)=>x.first).toList();return page([Text('أهلاً ${data.displayName}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const Text('نجم لا يعرض لك كل شيء؛ يخبرك ماذا تفعل الآن.',style:TextStyle(color:Colors.white54)),const SizedBox(height:14),box(Row(children:[SizedBox(width:72,height:72,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:score/100,color:gold,backgroundColor:panel2,strokeWidth:8),Text('$score%',style:const TextStyle(fontWeight:FontWeight.w900))])),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('درجة الالتزام اليوم',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Text('XP $xp • تركيز $focusToday دقيقة',style:const TextStyle(color:Colors.white60))]))])),title('ماذا أفعل الآن؟','ابدأ أصغر خطوة تخدم أهم نتيجة.'),box(n==null?Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('لا توجد مهمة مفتوحة الآن.',style:TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:8),FilledButton(onPressed:addTask,child:const Text('أضف أول خطوة'))]):Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(n.title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(n.remindAt==null?'ابدأ الآن': 'تذكير ${fmtTime(n.remindAt)}',style:const TextStyle(color:Colors.white60)),const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:gold,foregroundColor:Colors.black),onPressed:()=>focus(n),icon:const Icon(Icons.play_arrow),label:const Text('ابدأ 5 دقائق'))),const SizedBox(width:8),IconButton.filledTonal(onPressed:()=>done(n),icon:const Icon(Icons.check))])])),title('الثلاثة الأهم اليوم','لا تضف مهمة رابعة قبل إنهاء واحدة.'),if(ts.isEmpty)box(const Text('أضف مهامك وسأرتب أهم ثلاث تلقائياً.',style:TextStyle(color:Colors.white60))),...ts.map(taskTile),if(data.dreams.any((d)=>!d.readToday))...[title('ثبّت رؤيتك','اقرأ مستقبلك ثم اربطه بفعل اليوم.'),box(OutlinedButton.icon(onPressed:ritual,icon:const Icon(Icons.visibility),label:const Text('طقس الرؤية اليومي')))],title('محاسبة اليوم','راقب السلوك، لا المزاج.'),box(OutlinedButton.icon(onPressed:review,icon:const Icon(Icons.fact_check),label:const Text('مراجعة نهاية اليوم')))]);}
  Widget taskTile(TaskItem t)=>box(CheckboxListTile(contentPadding:EdgeInsets.zero,value:t.done,onChanged:(v)=>v==true?done(t):null,title:Text(t.title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(t.remindAt==null?'بدون تذكير':'${fmtTime(t.remindAt)} • أولوية ${t.priority}',style:const TextStyle(color:Colors.white54))));
  Widget goals()=>page([title('أهدافي','حوّل الحلم إلى نتيجة ثم خطوات.'),FilledButton.icon(onPressed:addGoal,icon:const Icon(Icons.add),label:const Text('هدف جديد')),const SizedBox(height:12),if(data.goals.isEmpty)box(const Text('ابدأ بهدف واحد مهم.',style:TextStyle(color:Colors.white60))),...data.goals.map((g)=>box(Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Expanded(child:Text(g.title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900))),Text('${(g.progress*100).round()}%',style:const TextStyle(color:gold2,fontWeight:FontWeight.w900))]),if(g.why.isNotEmpty)Padding(padding:const EdgeInsets.only(top:6),child:Text('لماذا؟ ${g.why}',style:const TextStyle(color:Colors.white60))),const SizedBox(height:10),LinearProgressIndicator(value:g.progress,color:gold,backgroundColor:panel2,minHeight:8),const SizedBox(height:8),...List.generate(g.steps.length,(i)=>CheckboxListTile(contentPadding:EdgeInsets.zero,dense:true,value:i<g.done.length?g.done[i]:false,onChanged:(v){while(g.done.length<g.steps.length)g.done.add(false);g.done[i]=v==true;g.progress=g.steps.isEmpty?0:g.done.where((x)=>x).length/g.steps.length;changed(v==true?8:0);},title:Text(g.steps[i]))),OutlinedButton.icon(onPressed:()=>taskFromGoal(g),icon:const Icon(Icons.bolt),label:const Text('حوّل الخطوة التالية لمهمة اليوم'))])))]);
  Widget vision()=>page([title('رؤيتي وأحلامي','صورة مستقبلية واضحة + فعل يومي.'),FilledButton.icon(onPressed:addDream,icon:const Icon(Icons.add),label:const Text('أضف حلمًا')),const SizedBox(height:12),...data.dreams.map((d)=>box(Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(d.title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),if(d.scene.isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Text(d.scene,style:const TextStyle(color:Colors.white70,height:1.5))),if(d.identity.isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Text('أنا أصبح: ${d.identity}',style:const TextStyle(color:gold2,fontWeight:FontWeight.w800))),const SizedBox(height:10),FilledButton.tonal(onPressed:(){d.readToday=true;changed(4);},child:Text(d.readToday?'قرأت رؤيتي اليوم ✓':'قرأت وتخيّلت اليوم'))]))),if(data.dreams.isNotEmpty)OutlinedButton.icon(onPressed:ritual,icon:const Icon(Icons.visibility),label:const Text('ابدأ طقس الرؤية'))]);
  Widget habits()=>page([title('عاداتي','ابنِ ما يخدمك واقطع الحلقة التي تعيدك للخلف.'),FilledButton.icon(onPressed:addHabit,icon:const Icon(Icons.add),label:const Text('عادة جديدة')),const SizedBox(height:12),...data.habits.map((h)=>box(Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Icon(h.quit?Icons.shield:Icons.trending_up,color:h.quit?danger:success),const SizedBox(width:8),Expanded(child:Text(h.name,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900))),Text('🔥 ${h.streak}',style:const TextStyle(color:gold2,fontWeight:FontWeight.w900))]),if(h.replacement.isNotEmpty)Padding(padding:const EdgeInsets.only(top:6),child:Text('البديل: ${h.replacement}',style:const TextStyle(color:Colors.white60))),const SizedBox(height:10),Row(children:[Expanded(child:FilledButton.tonal(onPressed:()=>habitDone(h),child:Text(h.quit?'تجاوزتها اليوم':'أنجزتها اليوم'))),if(h.quit)...[const SizedBox(width:8),OutlinedButton(onPressed:()=>rescue(h),child:const Text('أنقذني'))]])])))]);
  Widget coach()=>page([title('مرشد نجم','يسمعك، يقرأ بياناتك، ثم يعطيك خطوة عملية.'),box(Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('تشخيص اليوم: $score%',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(next==null?'رتّب خطوة جديدة تخدم أهم هدف.':'الآن: ${next!.title}',style:const TextStyle(color:Colors.white60)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:[ActionChip(label:const Text('أنا ضايع'),onPressed:()=>ask('أنا ضايع. قل لي ماذا أفعل الآن؟')),ActionChip(label:const Text('رتب يومي'),onPressed:()=>ask('رتب يومي حسب أهدافي ومهامي الحالية')),ActionChip(label:const Text('حاسبني'),onPressed:()=>ask('حاسبني على التزامي اليوم بصراحة وباختصار')),ActionChip(label:const Text('ضعفت بعادة'),onPressed:()=>ask('أنا على وشك أرجع لعادتي السيئة. ساعدني الآن'))])])),...chat.map((m)=>Align(alignment:m['role']=='user'?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:m['role']=='user'?const Color(0x22E8B84E):panel,borderRadius:BorderRadius.circular(16),border:Border.all(color:border)),child:Text(m['text']??'',style:const TextStyle(height:1.5))))),box(TextField(onSubmitted:(v){if(v.trim().isNotEmpty)ask(v.trim());},decoration:const InputDecoration(hintText:'اكتب لنجم: أنا متأخر، محبط، مشتت...')))]);
  Future<void> ask(String msg) async {chat.add({'role':'user','text':msg});changed(0);try{final r=await sb.functions.invoke('najm-coach',body:{'message':msg,'state':data.toJson(),'score':score,'focusToday':focusToday});final d=Map<String,dynamic>.from(r.data as Map);chat.add({'role':'assistant','text':'${d['reply']??'ابدأ بخمس دقائق على أهم خطوة.'}'});}catch(_){chat.add({'role':'assistant','text':'خلينا نرجع لخطوة واحدة: ${next?.title??'اكتب أهم مهمة ثم ابدأها لخمس دقائق'}.'});}changed(0);}
  Future<void> done(TaskItem t) async {t.done=true;top.remove(t.id);try{await ExactReminderService.instance.cancel(ExactReminderService.instance.idFor(t.id));}catch(_){}changed(12);}
  Future<void> focus(TaskItem t) async {focusToday+=5;changed(5);await ask('بدأت 5 دقائق على المهمة: ${t.title}. شجعني بجملة قصيرة وخطوة واحدة.');}
  Future<void> addTask() async {final c=TextEditingController();int mins=5;final ok=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setL)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:const Text('مهمة جديدة'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:c,autofocus:true,decoration:const InputDecoration(labelText:'ما الذي ستفعله؟')),const SizedBox(height:10),DropdownButtonFormField<int>(value:mins,decoration:const InputDecoration(labelText:'ذكّرني'),items:const [DropdownMenuItem(value:5,child:Text('بعد 5 دقائق')),DropdownMenuItem(value:15,child:Text('بعد 15 دقيقة')),DropdownMenuItem(value:60,child:Text('بعد ساعة')),DropdownMenuItem(value:0,child:Text('بدون تذكير'))],onChanged:(v)=>setL(()=>mins=v??0))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('إضافة'))]))));if(ok!=true||c.text.trim().isEmpty)return;final t=TaskItem(id:uid(),title:c.text.trim(),priority:2,remindAt:mins==0?null:DateTime.now().add(Duration(minutes:mins)));data.tasks.add(t);rebuild();if(t.remindAt!=null){try{await ExactReminderService.instance.requestPermissions();await ExactReminderService.instance.schedule(id:ExactReminderService.instance.idFor(t.id),when:t.remindAt!,title:'نجم يذكّرك ✦',body:t.title);await ExactReminderService.instance.schedule(id:ExactReminderService.instance.idFor(t.id)+900000,when:t.remindAt!.add(const Duration(minutes:10)),title:'لسه ما بدأت؟',body:'ابدأ 5 دقائق فقط: ${t.title}');}catch(_){}}changed(2);}
  Future<void> addGoal() async {final a=TextEditingController(),b=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(x)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:const Text('هدف جديد'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,decoration:const InputDecoration(labelText:'الهدف')),const SizedBox(height:10),TextField(controller:b,decoration:const InputDecoration(labelText:'لماذا مهم؟'))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('إنشاء'))])));if(ok==true&&a.text.trim().isNotEmpty){data.goals.add(GoalItem(id:uid(),title:a.text.trim(),why:b.text.trim(),steps:['حدد النتيجة بوضوح','أنجز أول خطوة صغيرة','راجع التقدم أسبوعياً','نفّذ خطوة اليوم'],done:[false,false,false,false]));changed(4);}}
  Future<void> taskFromGoal(GoalItem g) async {var text='راجع تقدم هدف: ${g.title}';for(var i=0;i<g.steps.length;i++){if(i>=g.done.length||!g.done[i]){text=g.steps[i];break;}}final t=TaskItem(id:uid(),title:text,priority:3,remindAt:DateTime.now().add(const Duration(minutes:5)));data.tasks.add(t);rebuild();try{await ExactReminderService.instance.requestPermissions();await ExactReminderService.instance.schedule(id:ExactReminderService.instance.idFor(t.id),when:t.remindAt!,title:'خطوة نحو ${g.title}',body:text);}catch(_){}changed(3);}
  Future<void> addDream() async {final a=TextEditingController(),b=TextEditingController(),d=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(x)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:const Text('حلم جديد'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,decoration:const InputDecoration(labelText:'الحلم')),const SizedBox(height:10),TextField(controller:b,maxLines:3,decoration:const InputDecoration(labelText:'مشهد من مستقبلك')),const SizedBox(height:10),TextField(controller:d,decoration:const InputDecoration(labelText:'من الشخص الذي ستصبحه؟'))])),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('حفظ'))])));if(ok==true&&a.text.trim().isNotEmpty){data.dreams.add(DreamItem(id:uid(),title:a.text.trim(),scene:b.text.trim(),identity:d.text.trim()));changed(4);}}
  Future<void> ritual() async {await showDialog<void>(context:context,builder:(x)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:const Text('طقس الرؤية — دقيقتان'),content:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[const Text('اقرأ ببطء، تخيّل التفاصيل، ثم اختر فعلاً واحداً لليوم.',style:TextStyle(color:Colors.white60)),const SizedBox(height:12),...data.dreams.map((d)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(d.title,style:const TextStyle(color:gold2,fontWeight:FontWeight.w900)),if(d.scene.isNotEmpty)Text(d.scene,style:const TextStyle(height:1.5)),if(d.identity.isNotEmpty)Text('هويتي: ${d.identity}',style:const TextStyle(color:Colors.white60))]))])),actions:[FilledButton(onPressed:(){for(final d in data.dreams)d.readToday=true;changed(8);Navigator.pop(x);},child:const Text('قرأتها وسأتحرك اليوم'))])));}
  Future<void> addHabit() async {final a=TextEditingController(),b=TextEditingController();bool quit=false;final ok=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setL)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:const Text('عادة جديدة'),content:Column(mainAxisSize:MainAxisSize.min,children:[SegmentedButton<bool>(segments:const [ButtonSegment(value:false,label:Text('أبني')),ButtonSegment(value:true,label:Text('أترك'))],selected:{quit},onSelectionChanged:(s)=>setL(()=>quit=s.first)),const SizedBox(height:10),TextField(controller:a,decoration:const InputDecoration(labelText:'اسم العادة')),const SizedBox(height:10),TextField(controller:b,decoration:InputDecoration(labelText:quit?'السلوك البديل':'كيف تجعلها سهلة؟'))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('حفظ'))]))));if(ok==true&&a.text.trim().isNotEmpty){data.habits.add(HabitItem(id:uid(),name:a.text.trim(),quit:quit,replacement:b.text.trim()));changed(3);}}
  void habitDone(HabitItem h){if(h.checkedDay!=dayKey())h.streak++;h.checkedDay=dayKey();changed(8);} Future<void> rescue(HabitItem h)=>showDialog<void>(context:context,builder:(x)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:const Text('خطة إنقاذ 10 دقائق'),content:Text('ابتعد عن المحفز الآن. اشرب ماء. تحرك دقيقتين. نفّذ البديل: ${h.replacement.isEmpty?'نشاط قصير يغيّر حالتك':h.replacement}. لا تفاوض نفسك لعشر دقائق فقط.',style:const TextStyle(height:1.55)),actions:[FilledButton(onPressed:()=>Navigator.pop(x),child:const Text('سأتجاوزها الآن'))])));
  Future<void> review() async {final a=TextEditingController(text:data.todayWin),b=TextEditingController(text:data.todayLesson),d=TextEditingController(text:data.tomorrowFocus);final ok=await showDialog<bool>(context:context,builder:(x)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:Text('محاسبة اليوم — $score%'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:a,decoration:const InputDecoration(labelText:'أهم انتصار')),const SizedBox(height:8),TextField(controller:b,decoration:const InputDecoration(labelText:'أين قصّرت؟ وما الدرس؟')),const SizedBox(height:8),TextField(controller:d,decoration:const InputDecoration(labelText:'أهم تركيز للغد'))])),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('لاحقاً')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('احفظ محاسبتي'))])));if(ok==true){data.todayWin=a.text.trim();data.todayLesson=b.text.trim();data.tomorrowFocus=d.text.trim();changed(10);await ask('هذه مراجعتي اليوم: انتصاري ${data.todayWin}، درسي ${data.todayLesson}، وتركيزي غداً ${data.tomorrowFocus}. أعطني ملاحظة قصيرة.');}}
}
